#!/usr/bin/env python3
"""
today.py — renders dark_mode.svg / light_mode.svg: a neofetch-style GitHub profile card.

Run locally:            GITHUB_TOKEN=ghp_xxx python today.py
Preview without a token: python today.py          (uses placeholder numbers)

Concept inspired by Andrew6rant/Andrew6rant. Implementation is standalone.
"""

import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

import requests

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG — this is the only part you normally need to touch
# ─────────────────────────────────────────────────────────────────────────────

USERNAME = "4mohdisa"
PROMPT = "isa@github"          # the header line, like a shell prompt

# "Uptime" source. Leave as None to use your GitHub account age,
# or set to "YYYY-MM-DD" (e.g. your birthday) to count from that date instead.
UPTIME_FROM = None

INCLUDE_FORKS = False          # count forked repos in the repo/LOC totals

# Repos to skip when counting lines of code. Useful for anything where a big
# vendored folder (node_modules, datasets, build output) got committed once and
# removed later — it swamps the real number without meaning anything.
LOC_EXCLUDE = {"SignFlow"}
ASCII_FILE = "ascii_art.txt"   # generated by make_ascii.py
CACHE_FILE = "cache/loc_cache.json"

# Static rows. Stats rows are appended automatically below.
# Types: ("head", text) ("sec", title) ("kv", key, value) ("gap",)
STATIC_ROWS = [
    ("kv", "OS", "macOS, Ubuntu, Windows 11"),
    ("kv", "Uptime", "{UPTIME}"),
    ("kv", "Host", "Magain Real Estate, Adelaide"),
    ("kv", "Kernel", "Property Manager / Solo Founder"),
    ("kv", "IDE", "VS Code, Cursor, Claude Code"),
    ("gap",),
    ("kv", "Languages.Programming", "TypeScript, Python, Rust, Dart"),
    ("kv", "Languages.Computer", "HTML, CSS, SQL, JSON, YAML"),
    ("kv", "Languages.Real", "English, Urdu, Hindi"),
    ("gap",),
    ("kv", "Shipped.SaaS", "Applyable, Mindbase, DataVisual"),
    ("kv", "Shipped.Tools", "Motionaire, TrackrAI, IdeaRadar"),
    ("kv", "Stack.Cloud", "AWS EC2, Vercel, Supabase, Caddy"),
    ("gap",),
    ("sec", "Contact"),
    ("kv", "Email.Personal", "isaxxcode@gmail.com"),
    ("kv", "Website", "isaxcode.com"),
    ("kv", "LinkedIn", "4mohdisa"),
    ("kv", "X", "4mohdisa"),
    ("kv", "YouTube", "IsaXcode"),
    ("gap",),
]

# ─────────────────────────────────────────────────────────────────────────────
# LAYOUT
# ─────────────────────────────────────────────────────────────────────────────

FONT = "ui-monospace,'SF Mono','Cascadia Mono','Roboto Mono',Menlo,Consolas,'Courier New',monospace"
FONT_SIZE = 13
CHAR_W = 7.8
LINE_H = 16.4
ASCII_COLS = 44          # recalculated from ascii_art.txt at runtime
INFO_COLS = 62

PAD = 30
GUTTER = 34
ASCII_X = PAD
TOP = 50
INFO_X = PAD + ASCII_COLS * CHAR_W + GUTTER
WIDTH = int(INFO_X + INFO_COLS * 8.05 + PAD)   # 8.05 leaves slack for wider mono fonts
HEIGHT = int(TOP + 33 * LINE_H + PAD)


def fit_canvas(ascii_lines, info_rows):
    """Size the card to whatever the ASCII art and the info column actually need."""
    global ASCII_COLS, INFO_X, WIDTH, HEIGHT
    ASCII_COLS = max((len(l) for l in ascii_lines), default=40)
    INFO_X = PAD + ASCII_COLS * CHAR_W + GUTTER
    WIDTH = int(INFO_X + INFO_COLS * 8.05 + PAD)
    HEIGHT = int(TOP + max(len(ascii_lines), info_rows) * LINE_H + PAD)

THEMES = {
    "dark_mode": dict(
        outer="#010409", panel="#0d1117", stroke="#21262d",
        art_a="#d6dde6", art_b="#7d8896", prompt="#e6edf3", rule="#30363d",
        key="#f0883e", dot="#2a3038", val="#79c0ff", accent="#58a6ff",
        add="#3fb950", sub="#f85149", muted="#8b949e",
    ),
    "light_mode": dict(
        outer="#ffffff", panel="#f6f8fa", stroke="#d0d7de",
        art_a="#3d444d", art_b="#8c959f", prompt="#1f2328", rule="#d0d7de",
        key="#953800", dot="#d8dee4", val="#0969da", accent="#0969da",
        add="#1a7f37", sub="#cf222e", muted="#59636e",
    ),
}

API = "https://api.github.com/graphql"


# ─────────────────────────────────────────────────────────────────────────────
# GitHub
# ─────────────────────────────────────────────────────────────────────────────

def gql(query, variables, token, tries=4):
    for attempt in range(tries):
        r = requests.post(
            API,
            json={"query": query, "variables": variables},
            headers={"Authorization": f"bearer {token}"},
            timeout=60,
        )
        if r.status_code == 200 and "errors" not in r.json():
            return r.json()["data"]
        if attempt == tries - 1:
            raise RuntimeError(f"GitHub API failed: {r.status_code} {r.text[:400]}")
        time.sleep(2 ** attempt)


def fetch_profile(token):
    q = """
    query($login:String!){
      user(login:$login){
        id createdAt
        followers{totalCount}
        repositoriesContributedTo(contributionTypes:[COMMIT,PULL_REQUEST,REPOSITORY]){totalCount}
      }
    }"""
    return gql(q, {"login": USERNAME}, token)["user"]


def fetch_repos(token):
    q = """
    query($login:String!,$cursor:String){
      user(login:$login){
        repositories(first:100, ownerAffiliations:OWNER, after:$cursor,
                     orderBy:{field:STARGAZERS, direction:DESC}){
          totalCount
          pageInfo{hasNextPage endCursor}
          nodes{
            name owner{login} isFork stargazerCount
            defaultBranchRef{ target{ ... on Commit { oid } } }
          }
        }
      }
    }"""
    repos, cursor = [], None
    total = 0
    while True:
        data = gql(q, {"login": USERNAME, "cursor": cursor}, token)["user"]["repositories"]
        total = data["totalCount"]
        repos.extend(data["nodes"])
        if not data["pageInfo"]["hasNextPage"]:
            break
        cursor = data["pageInfo"]["endCursor"]
    if not INCLUDE_FORKS:
        repos = [r for r in repos if not r["isFork"]]
    return repos, total


def fetch_commits(token, created_at):
    q = """
    query($login:String!,$from:DateTime!,$to:DateTime!){
      user(login:$login){
        contributionsCollection(from:$from,to:$to){
          totalCommitContributions
          restrictedContributionsCount
        }
      }
    }"""
    start = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
    now = datetime.now(timezone.utc)
    total = 0
    year = start.year
    while year <= now.year:
        frm = max(start, datetime(year, 1, 1, tzinfo=timezone.utc))
        to = min(now, datetime(year, 12, 31, 23, 59, 59, tzinfo=timezone.utc))
        c = gql(q, {"login": USERNAME, "from": frm.isoformat(), "to": to.isoformat()},
                token)["user"]["contributionsCollection"]
        total += c["totalCommitContributions"] + c["restrictedContributionsCount"]
        year += 1
    return total


def fetch_loc(token, user_id, repos):
    """Additions/deletions authored by you, cached per repo HEAD so reruns are cheap."""
    q = """
    query($owner:String!,$name:String!,$id:ID!,$cursor:String){
      repository(owner:$owner,name:$name){
        defaultBranchRef{ target{ ... on Commit {
          history(first:100, author:{id:$id}, after:$cursor){
            pageInfo{hasNextPage endCursor}
            nodes{ additions deletions }
          }
        }}}
      }
    }"""
    cache_path = Path(CACHE_FILE)
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache = json.loads(cache_path.read_text()) if cache_path.exists() else {}

    add = sub = 0
    for r in repos:
        if r["name"] in LOC_EXCLUDE:
            continue
        ref = r.get("defaultBranchRef")
        if not ref or not ref.get("target"):
            continue
        key = f"{r['owner']['login']}/{r['name']}"
        head = ref["target"]["oid"]
        hit = cache.get(key)
        if hit and hit.get("head") == head:
            add += hit["add"]
            sub += hit["sub"]
            continue

        a = s = 0
        cursor = None
        while True:
            d = gql(q, {"owner": r["owner"]["login"], "name": r["name"],
                        "id": user_id, "cursor": cursor}, token)
            ref_ = (d.get("repository") or {}).get("defaultBranchRef") or {}
            hist = (ref_.get("target") or {}).get("history")
            if not hist:
                break
            for n in hist["nodes"]:
                a += n["additions"]
                s += n["deletions"]
            if not hist["pageInfo"]["hasNextPage"]:
                break
            cursor = hist["pageInfo"]["endCursor"]

        cache[key] = {"head": head, "add": a, "sub": s}
        add += a
        sub += s

    cache_path.write_text(json.dumps(cache, indent=1, sort_keys=True))
    return add, sub


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def uptime_string(start_iso):
    start = datetime.fromisoformat(start_iso.replace("Z", "+00:00"))
    now = datetime.now(timezone.utc)
    y = now.year - start.year
    m = now.month - start.month
    d = now.day - start.day
    if d < 0:
        m -= 1
        prev = (now.month - 1) or 12
        days_in = [31, 29 if now.year % 4 == 0 else 28, 31, 30, 31, 30,
                   31, 31, 30, 31, 30, 31][prev - 1]
        d += days_in
    if m < 0:
        y -= 1
        m += 12

    def plural(n, w):
        return f"{n} {w}" + ("" if n == 1 else "s")

    return f"{plural(y,'year')}, {plural(m,'month')}, {plural(d,'day')}"


def commafy(n):
    return f"{n:,}"


# ─────────────────────────────────────────────────────────────────────────────
# SVG
# ─────────────────────────────────────────────────────────────────────────────

_T = {}  # active theme, set by render()


def seg(cls, text):
    extra = ' font-weight="700"' if cls == "prompt" else ""
    return f'<tspan fill="{_T[cls]}"{extra}>{escape(text)}</tspan>'


def row_head(text):
    fill = INFO_COLS - len(text) - 1
    return seg("prompt", text) + seg("rule", " " + "─" * max(fill, 1))


def row_sec(title):
    fill = INFO_COLS - len(title) - 4
    return seg("rule", "─ ") + seg("prompt", title) + seg("rule", " " + "─" * max(fill, 1))


def row_kv(key, value):
    dots = INFO_COLS - len(key) - len(value) - 5
    return (seg("key", "· ") + seg("key", key + ":")
            + seg("dot", " " + "." * max(dots, 1) + " ")
            + seg("val", value))


def half_kv(key, value, width, val_cls="val"):
    dots = width - len(key) - len(value) - 3
    return (seg("key", key + ":") + seg("dot", " " + "." * max(dots, 1) + " ")
            + seg(val_cls, value))


def render(theme_name, ascii_lines, stats):
    t = THEMES[theme_name]
    _T.clear()
    _T.update(t)

    rows = [("head", PROMPT)] + [
        r if r[0] != "kv" else ("kv", r[1], r[2].replace("{UPTIME}", stats["uptime"]))
        for r in STATIC_ROWS
    ]

    body = []
    for r in rows:
        if r[0] == "head":
            body.append(row_head(r[1]))
        elif r[0] == "sec":
            body.append(row_sec(r[1]))
        elif r[0] == "kv":
            body.append(row_kv(r[1], r[2]))
        else:
            body.append(seg("key", "·"))

    # stats block
    body.append(row_sec("GitHub Stats"))
    contributed = " {Contributed: " + str(stats["contrib"]) + "}"
    body.append(
        seg("key", "· ")
        + half_kv("Repos", str(stats["repos"]), 34 - len(contributed))
        + seg("muted", " {Contributed: ") + seg("val", str(stats["contrib"])) + seg("muted", "}")
        + seg("muted", " | ")
        + half_kv("Stars", commafy(stats["stars"]), 23)
    )
    body.append(
        seg("key", "· ")
        + half_kv("Commits", commafy(stats["commits"]), 34)
        + seg("muted", " | ")
        + half_kv("Followers", commafy(stats["followers"]), 23)
    )
    net = commafy(stats["add"] - stats["sub"])
    tail = f" ( {commafy(stats['add'])}++, {commafy(stats['sub'])}-- )"
    body.append(
        seg("key", "· ")
        + half_kv("Lines of Code on GitHub", net, INFO_COLS - 2 - len(tail))
        + seg("muted", " ( ") + seg("add", commafy(stats["add"]) + "++")
        + seg("muted", ", ") + seg("sub", commafy(stats["sub"]) + "--") + seg("muted", " )")
    )

    art = "".join(
        f'<text x="{ASCII_X}" y="{TOP + i * LINE_H:.1f}" fill="url(#artGrad)" xml:space="preserve">'
        f"{escape(line)}</text>"
        for i, line in enumerate(ascii_lines)
    )
    info = "".join(
        f'<text x="{INFO_X:.0f}" y="{TOP + i * LINE_H:.1f}" xml:space="preserve">{line}</text>'
        for i, line in enumerate(body)
    )

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-label="{USERNAME} GitHub profile card">
  <defs>
    <linearGradient id="artGrad" x1="0" y1="0" x2="0.35" y2="1">
      <stop offset="0%" stop-color="{t['art_a']}"/>
      <stop offset="100%" stop-color="{t['art_b']}"/>
    </linearGradient>
  </defs>
  <rect width="{WIDTH}" height="{HEIGHT}" rx="10" fill="{t['outer']}"/>
  <rect x="12" y="12" width="{WIDTH - 24}" height="{HEIGHT - 24}" rx="8" fill="{t['panel']}" stroke="{t['stroke']}"/>
  <g font-family="{FONT}" font-size="{FONT_SIZE}px">
  {art}
  {info}
  </g>
</svg>
"""


# ─────────────────────────────────────────────────────────────────────────────

def main():
    ascii_lines = Path(ASCII_FILE).read_text(encoding="utf-8").rstrip("\n").split("\n")

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("ACCESS_TOKEN")
    if not token:
        print("No GITHUB_TOKEN set — rendering a preview with placeholder numbers.")
        stats = dict(uptime="4 years, 2 months, 11 days", repos=42, contrib=18,
                     stars=210, commits=3120, followers=96, add=520000, sub=180000)
    else:
        profile = fetch_profile(token)
        repos, repo_total = fetch_repos(token)
        add, sub = fetch_loc(token, profile["id"], repos)
        stats = dict(
            uptime=uptime_string(UPTIME_FROM + "T00:00:00Z" if UPTIME_FROM else profile["createdAt"]),
            repos=len(repos) if not INCLUDE_FORKS else repo_total,
            contrib=profile["repositoriesContributedTo"]["totalCount"],
            stars=sum(r["stargazerCount"] for r in repos),
            commits=fetch_commits(token, profile["createdAt"]),
            followers=profile["followers"]["totalCount"],
            add=add, sub=sub,
        )

    fit_canvas(ascii_lines, len(STATIC_ROWS) + 5)
    for name in THEMES:
        Path(f"{name}.svg").write_text(render(name, ascii_lines, stats), encoding="utf-8")
        print(f"wrote {name}.svg")


if __name__ == "__main__":
    sys.exit(main())
